#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Toasts.Forms.Plugin.Sample.Droid.Resource", IsApplication=true)]

namespace Toasts.Forms.Plugin.Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Toasts.Resource.Drawable.error = global::Toasts.Forms.Plugin.Sample.Droid.Resource.Drawable.error;
			global::Toasts.Resource.Drawable.info = global::Toasts.Forms.Plugin.Sample.Droid.Resource.Drawable.info;
			global::Toasts.Resource.Drawable.success = global::Toasts.Forms.Plugin.Sample.Droid.Resource.Drawable.success;
			global::Toasts.Resource.Drawable.warning = global::Toasts.Forms.Plugin.Sample.Droid.Resource.Drawable.warning;
			global::Toasts.Resource.Id.desc = global::Toasts.Forms.Plugin.Sample.Droid.Resource.Id.desc;
			global::Toasts.Resource.Id.image = global::Toasts.Forms.Plugin.Sample.Droid.Resource.Id.image;
			global::Toasts.Resource.Id.title = global::Toasts.Forms.Plugin.Sample.Droid.Resource.Id.title;
			global::Toasts.Resource.Layout.crouton = global::Toasts.Forms.Plugin.Sample.Droid.Resource.Layout.crouton;
			global::Toasts.Resource.String.ApplicationName = global::Toasts.Forms.Plugin.Sample.Droid.Resource.String.ApplicationName;
			global::Toasts.Resource.String.Hello = global::Toasts.Forms.Plugin.Sample.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::Toasts.Forms.Plugin.Sample.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::Toasts.Forms.Plugin.Sample.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int error = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int info = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int success = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int warning = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int desc = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int image = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int title = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int crouton = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
